### ISSUE TITLE
Timezone mismatch between client and broker

### ISSUE THREAD

**Issue by headcloudmonkey** [tsi-software/Secure_ESP8266_MQTT_poc#2]
Noted that the NTP setup for 'SetupWifi.cpp' assumes a western US (GMT-8) timezone. If your server is not on this, the client will not connect correctly. You will see it keep attempting and the /var/log/messages on the broker will state Socket error.

Adjust the line:
configTime(8 * 3600, 0, "pool.ntp.org", "time.nist.gov", "time.windows.com");

For me, I use UTC everywhere, so this would be:
configTime(0 , 0, "pool.ntp.org", "time.nist.gov", "time.windows.com");

**Comment by tsi-software** [comment]
Thanks headcloudmonkey. I fully agree that UTC is the way to go. I missed that one. It avoids so many potential problems with mismatched time zones and daylight savings time . I have pushed a commit with that revision.
